# API

## Data Structures

### User
+ _id : 5d113sdfsdfsdfd15f4a19
+ updatedAt : 2019-10-23T01:44:51.341Z
+ createdAt : 2019-06-24T21:05:15.045Z
+ name : Codi 8plus

## Get All Users [/user/all]

### Get all users [GET]
Send authorization header to get users list.

+ Response 200 (application/json)

    + Attributes (array [User])
      - (User)
      - (User)
